### ISSUE TITLE
Error: module not found:  app/build/index.js

### ISSUE THREAD

**Issue by PhantomGuru0427** [flaviuse/mern-authentication#173]
docker compose -f docker-compose.prod.yml --env-file client.prod.env up --build
I am trying to run this command for production mode, but it caused error.
In server, docker file is CMD ["yarn", "start:prod"]
package.json is 
 "scripts": {
    "build": "tsc-alias --project tsconfig.json",
    "dev": "ts-node-dev --respawn -r tsconfig-paths/register index.ts",
    "start": "yarn build && node build/index.js",
    "start:prod": "node build/index.js",
    "ci": "yarn install --frozen-lockfile"
  },

**Comment by muhammadbasitobaid** [comment]
Hi @flaviuse I guess the outDir path is wrong in the server/tsconfig.json instead of "build" it should be "./build". because of this the build folder is not created as the yarn run build doesn't give any error and runs successfully, it's causing confusion! you can either fix it up yourself or maybe I can provide you with a small pr!

**Comment by muhammadbasitobaid** [comment]
Hi @flaviuse i guess you need to update the build script in package.json according to tsc-alias documentation:
`"build": "tsc --project tsconfig.json && tsc-alias -p tsconfig.json",` should do it!

**Comment by flaviuse** [comment]
Thank you for your suggestion @muhammadbasitobaid I have fixed the issue in #191
